### ISSUE TITLE
Lint main file

### ISSUE THREAD

**Issue by simonsmith** [suitcss/preprocessor#41]
Currently if I pass this component:

``` css
/** @define Component */

@import "./util.css";

@custom-media --media-query (min-width: 200px);

:root {
  --Component-size: 16px;
}

.Component {
  font-size: var(--Component-size);
  width: calc(100% * 1 / 6);
}

.Component-item {
  display: flex;
}

@media (--media-query) {
  .Component-item {
    color: red;
  }
}
```

Only the `util.css` will be linted. Would be nice to lint the main file too.
